version: '3'
services:
  application:
    container_name: chekirout-springboot-dev
    image: ${DOCKER_REPOSITORY}:latest
    environment:
      - VAULT_URI=${VAULT_URI}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_BACKEND=${VAULT_BACKEND}
      - VAULT_DEFAULT_CONTEXT=${VAULT_DEFAULT_CONTEXT}
    ports:
      - "8080:8080"
    restart: on-failure
    logging:
      driver: awslogs
      options:
        awslogs-group: "cloudwatch-log"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "chekirout-springboot-be"
    networks:
      - chekirout-network  # 네트워크 연결 추가

  nginx:
    container_name: nginx
    image: ${DOCKER_REPOSITORY_NGINX}:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - application
    networks:
      - chekirout-network  # 네트워크 연결 추가

networks:
  chekirout-network:
    driver: bridge