version: '3'
services:
  application:
    container_name: chekirout-springboot-dev
    image: ${DOCKER_REPOSITORY}:latest
    environment:
      - VAULT_URI=${VAULT_URI}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_BACKEND=${VAULT_BACKEND}
      - VAULT_DEFAULT_CONTEXT=${VAULT_DEFAULT_CONTEXT}
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - chekirout-network  # 네트워크 연결 추가

  nginx:
    container_name: nginx
    image: ${DOCKER_REPOSITORY_NGINX}:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - application
    networks:
      - chekirout-network  # 네트워크 연결 추가

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - chekirout-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  chekirout-network:
    driver: bridge