spring:
  application:
    name: chekirout
  profiles:
    active:
      - local
    group:
      local:
        - db-local
#      dev:
#        - db-dev
#      prod:
#        - db-prod
    include:
      - db