# default
spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

--- # db-local
spring:
  config:
    activate:
      on-profile: "db-local"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chekirout
    username: root
    password: 1234
    p6spy:
      enabled: true
      appender: com.p6spy.engine.spy.appender.Slf4JLogger
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect