# default
spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
  # 이메일 SMTP 설정 (모든 환경에서 동일하게 사용할 경우)
  mail:
    host: smtp.gmail.com
    port: 587
    username: juheun9912@gmail.com
    password: haqx afaq vypv obre
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}



--- # db-local
spring:
  config:
    activate:
      on-profile: "db-local"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chekirout
    username: root
    password: root1234
    p6spy:
      enabled: true
      appender: com.p6spy.engine.spy.appender.Slf4JLogger
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

--- # db-dev
spring:
  config:
    activate:
      on-profile: "db-dev"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    p6spy:
      enabled: true
      appender: com.p6spy.engine.spy.appender.Slf4JLogger
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect




