name: Build and Test with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  checks: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    # 전역으로 사용할 Vault 환경 변수 설정
    env:
      VAULT_URI: ${{ secrets.VAULT_URI }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      VAULT_BACKEND: ${{ secrets.VAULT_BACKEND }}
      VAULT_DEFAULT_CONTEXT: ${{ secrets.VAULT_DEFAULT_CONTEXT }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 환경 변수가 제대로 설정되었는지 출력 (디버깅용)
      - name: Print Vault Environment Variables
        run: |
          echo "VAULT_URI: $VAULT_URI"
          echo "VAULT_TOKEN: $VAULT_TOKEN"
          echo "VAULT_BACKEND: $VAULT_BACKEND"
          echo "VAULT_DEFAULT_CONTEXT: $VAULT_DEFAULT_CONTEXT"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0

      - name: Build and Test with Gradle
        run: |
          ./gradlew build
          ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: build/test-results/**/*.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'